
-- DDLs

DROP TABLE Movie CASCADE;
DROP TABLE Genre CASCADE;
DROP TABLE Actor CASCADE;
DROP TABLE Genre_of CASCADE;
DROP TABLE Episode CASCADE;
DROP TABLE Version CASCADE;
DROP TABLE Account CASCADE;
DROP TABLE Rating CASCADE;
DROP TABLE Admin CASCADE;
DROP TABLE Membership CASCADE;
DROP TABLE Actor_of CASCADE;

CREATE TABLE Movie(
	Movie_id SERIAL PRIMARY KEY,
	Original_title VARCHAR(200) NOT NULL,
	Primary_title VARCHAR(200),
	Running_time NUMERIC(5,0),
	Start_year DATE,
	End_year DATE, 
	Type VARCHAR(20) NOT NULL,
	Is_adult BOOLEAN NOT NULL,
	Rating NUMERIC(3,1)
);

CREATE TABLE Genre(
	Genre_id SERIAL NOT NULL PRIMARY KEY,
	Genre VARCHAR(20) NOT NULL
);

CREATE TABLE Genre_of(
	mid INTEGER NOT NULL,
	gen INTEGER NOT NULL,
	PRIMARY KEY(mid, gen),
	CONSTRAINT GENRE_OF_Movie_id FOREIGN KEY (mid) REFERENCES Movie (Movie_id) ON DELETE CASCADE,
	CONSTRAINT GENRE_OF_Genre_id FOREIGN KEY (gen) REFERENCES Genre (Genre_id) ON DELETE CASCADE
);

CREATE TABLE Actor(
	Actor_id SERIAL NOT NULL PRIMARY KEY,
	Actor_name VARCHAR(50) NOT NULL,
	Birth_year NUMERIC(4,0),
	Death_year NUMERIC(4,0)
);

CREATE TABLE Actor_of(
	aid INTEGER NOT NULL,
	mid INTEGER NOT NULL,
	Character VARCHAR(100),
	PRIMARY KEY(aid, mid),
	CONSTRAINT ACTOR_OF_Movie_id FOREIGN KEY (mid) REFERENCES Movie (Movie_id) ON DELETE CASCADE,
	CONSTRAINT ACTOR_OF_Actor_id FOREIGN KEY (aid) REFERENCES Actor (Actor_id) ON DELETE CASCADE
);



CREATE TABLE Episode(
	Episode_id SERIAL NOT NULL PRIMARY KEY,
	pid SERIAL NOT NULL,
	Episode_title VARCHAR(100) NOT NULL,
	Episode_number INTEGER,
	Episode_season INTEGER,
	CONSTRAINT EPISODE_Parent_id FOREIGN KEY (pid) REFERENCES Movie (Movie_id) ON DELETE CASCADE
);

CREATE TABLE Version(
	Version_id SERIAL NOT NULL PRIMARY KEY,
	Version_title VARCHAR(200) NOT NULL,
	Region VARCHAR(50),
	Language VARCHAR(50),
	mid SERIAL NOT NULL,
	CONSTRAINT VERSION_Movie_id FOREIGN KEY (mid) REFERENCES Movie (Movie_id) ON DELETE CASCADE
);

CREATE TABLE Membership(
        Membership_id SERIAL NOT NULL PRIMARY KEY,
        Membership_name VARCHAR(10) NOT NULL
);

CREATE TABLE Account(
	Account_id SERIAL NOT NULL PRIMARY KEY,
	Email_add VARCHAR(100) NOT NULL UNIQUE,
	First_name VARCHAR(100) NOT NULL,
	Last_name VARCHAR(100) NOT NULL,
	Birthday DATE,
	Sex VARCHAR(20),
	Password VARCHAR(50) NOT NULL,
	Phone VARCHAR(20),
	Address VARCHAR(100),
	Job VARCHAR(100),
	sid SERIAL NOT NULL,
	CONSTRAINT ACCOUNT_Membership_id FOREIGN KEY (sid) REFERENCES Membership (Membership_id)
);

CREATE TABLE Rating(
	Rating_id SERIAL NOT NULL PRIMARY KEY,
	Single_rating INTEGER NOT NULL,
	mid SERIAL NOT NULL,
	uid SERIAL NOT NULL,
	CONSTRAINT RATING_Movie_id FOREIGN KEY (mid) REFERENCES Movie (Movie_id) ON DELETE CASCADE,
	CONSTRAINT RATING_Account_id FOREIGN KEY (uid) REFERENCES Account (Account_id) ON DELETE CASCADE
);

CREATE TABLE Admin(
	uid SERIAL NOT NULL,
	CONSTRAINT ADMIN_Account_id FOREIGN KEY (uid) REFERENCES Account (Account_id) ON DELETE CASCADE
);
